// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhiksxgtsjpygenuobcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoaWtzeGd0c2pweWdlbnVvYmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTgxMDYsImV4cCI6MjA2OTg5NDEwNn0.AbQT7yp2rqaeVGq6_tOAxTeBNR-wnk4sobAgXJhoZbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});